version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=blackmichiestudio
      - DB_USER=postgres
      - DB_PASSWORD=hola123
    # - NODE_ENV=production
    expose:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-net

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: blackmichiestudio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hola123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blackmichiestudio"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Para init en primer arranque (opcional):
    # - ./db/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - app-net

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    # - "443:443"  # cuando actives TLS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  pgdata:
